### ISSUE TITLE
Using Nexus OSS

### ISSUE THREAD

**Issue by sykim-etri** [m-cmp/mc-workflow-manager#1]
현재 내부 패키지 관리를 위한 저장소로 Nexus를 활용하고 계신 상황이며, 개발 범위 상 Nexus를 수정할 필요성은 없는 것으로 말씀주신 바 있습니다. 타 프로젝트에서도 유사한 이슈가 있기에 동일한 방향으로의 활용이 필요합니다.

* https://github.com/cloud-barista/cm-grasshopper/issues/4#issuecomment-2187962419

상기 내용을 검토하시고 의견 부탁드립니다. @pbcccbeatboard-strato

**Comment by pbcccbeatboard-strato** [comment]
안녕하세요 스트라토 김진욱입니다.

말씀해주신대로 Nexus는 추후에도 문제가 될 수 있어, 타 repo도 염두해두고있는 상황입니다.

활용방식에서 말씀해주신대로 현재 개발 중 필요기능들을 추상화하여
추후 관련 이슈가 발생했을 때에 해당 구현체를 변경하는 것을 감안하여 진행중입니다.
(다만 스트라토의 경우 현재 wrapper가 아닌 interface로 작성되어 있습니다.
혹시 wrapper로 통일을 원하실 경우 해당방향으로 진행하는 것을 상의하여 전달드리겠습니다.)

현재까지는 helm, deb, tar, container등의 저장소 활용성만 예정되어있어 확장개발은 염두해두지 않은 상황이며,
추후 라이선스 이슈나 기능상 확장개발이 부득이하게 필요할 경우
Nexus가 아닌 다른 sw나 다른 방식의 저장지원을 선택할 것 같습니다.

감사합니다.




From: Sooyoung Kim ***@***.***>
Sent: Tuesday, June 25, 2024 1:47 PM
To: m-cmp/mc-workflow-manager ***@***.***>
Cc: 김진욱 ***@***.***>; Mention ***@***.***>
Subject: [m-cmp/mc-workflow-manager] Using Nexus OSS (Issue #1)


현재 내부 패키지 관리를 위한 저장소로 Nexus를 활용하고 계신 상황이며, 개발 범위 상 Nexus를 수정할 필요성은 없는 것으로 말씀주신 바 있습니다. 타 프로젝트에서도 유사한 이슈가 있기에 동일한 방향으로의 활용이 필요합니다.

  *   cloud-barista/cm-grasshopper#4 (comment)<https://github.com/cloud-barista/cm-grasshopper/issues/4#issuecomment-2187962419>

상기 내용을 검토하시고 의견 부탁드립니다. @pbcccbeatboard-strato<https://github.com/pbcccbeatboard-strato>

**Comment by sykim-etri** [comment]
@pbcccbeatboard-strato 
구현 방식이 Wrapper로 통일될 필요는 없으며, 이슈 발생시 변경하기 용이한 구조면 괜찮겠습니다.
